spring:
  banner:
    location: inventario.txt
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: titan1386
    url: jdbc:mysql://localhost:3306/inventario?serverTimezone
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        hibernate:
      ddl-auto: none

server:
  port: 8085
springdoc:
  swagger-ui:
    path: /inventario.html